#!/bin/bash

GITIGNORE_PATH=~/.config/.gitignore

echo ">>> creating symbolic links"
ln -sfv ~/dotfiles/nvim ~/.config
ln -sfv ~/dotfiles/opencode ~/.config
ln -sfv ~/dotfiles/ghostty ~/.config
ln -sfv ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sfv ~/dotfiles/starship.toml ~/.config
ln -sfv ~/dotfiles/config.fish ~/.config/fish
ln -sfv ~/dotfiles/gitignore ~/.config/.gitignore
ln -sfv ~/dotfiles/.tmux-session-manager.sh ~/.tmux-session-manager.sh

echo ">>> setting up global .gitignore file: $GITIGNORE_PATH"
git config --global core.excludesfile $GITIGNORE_PATH

echo ">>> done"
