#!/bin/bash

ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
ln -sf ~/dotfiles/alacritty/color.yml ~/.config/alacritty/color.yml
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/starship.toml ~/.config
ln -sf ~/dotfiles/config.fish ~/.config/fish
ln -sf ~/dotfiles/gitignore ~/.config/.gitignore
